if (lvl = 14) or (lvl = 15) then
begin
  // rounded halls, twisted paths
  Part[1, 1]  := '^^^^^i^^^^^';
  Part[1, 2]  := '^^^^^i^^^^^';
  Part[1, 3]  := '^^^^i^^^^^^';
  Part[1, 4]  := '^^^i^^^^^^^';
  Part[1, 5]  := '^^iiii^^^^^';
  Part[1, 6]  := '^ii.iii^^ii';
  Part[1, 7]  := '^iii...ii^^';
  Part[1, 8]  := '^^iiii^^^^^';
  Part[1, 9]  := '^^^^i^^^^^^';
  Part[1, 10] := '^^^^^i^^^^^';
  Part[1, 11] := '^^^^^i^^^^^';

  Part[2, 1]  := '^^^^i^^^^^^';
  Part[2, 2]  := '^i^^i^^^^^^';
  Part[2, 3]  := '^i^^^ii^^^^';
  Part[2, 4]  := '^^i^^^^i^^^';
  Part[2, 5]  := 'i^^i^^^i^^i';
  Part[2, 6]  := 'iiicccc..ii';
  Part[2, 7]  := 'iii^^^^^^ii';
  Part[2, 8]  := '^i^^iiii^^^';
  Part[2, 9]  := '^iiiiiiiii^';
  Part[2, 10] := '^^^iiiiii^^';
  Part[2, 11] := '^^^^^i^^^^^';

  Part[3, 1]  := '^^^^^i^^^^^';
  Part[3, 2]  := '^^iiiiiii^^';
  Part[3, 3]  := '^iiiii..ii^';
  Part[3, 4]  := '^ii^iiii.i^';
  Part[3, 5]  := '^ii^^iiii.^';
  Part[3, 6]  := 'iiii^^^^iii';
  Part[3, 7]  := '^iiiiii^^^^';
  Part[3, 8]  := '^^^^iiiiii^';
  Part[3, 9]  := '^ii^^iiiii^';
  Part[3, 10] := '^^iiiiiii^^';
  Part[3, 11] := '^^^^^i^^^^^';

  Part[4, 1]  := '^^^^^i^^^^^';
  Part[4, 2]  := '^^^^^+^^^^^';
  Part[4, 3]  := '^^^cc..^^^^';
  Part[4, 4]  := '^.cc.^...^^';
  Part[4, 5]  := '^...^^^^..^';
  Part[4, 6]  := '....^^^^^..';
  Part[4, 7]  := '^...^^^^..^';
  Part[4, 8]  := '^....^^...^';
  Part[4, 9]  := '^^.......^^';
  Part[4, 10] := '^^^^^+^^^^^';
  Part[4, 11] := '^^^^^i^^^^^';

  Part[5, 1]  := '^^^^^i^^^^^';
  Part[5, 2]  := '^^^^^.^^^^^';
  Part[5, 3]  := '^^^i..ii^^^';
  Part[5, 4]  := '^iiii^^iii^';
  Part[5, 5]  := '^ii^^^^^ii^';
  Part[5, 6]  := 'ii^^^^^^^ii';
  Part[5, 7]  := '^ii^^^^^ii^';
  Part[5, 8]  := '^iii^^^iii^';
  Part[5, 9]  := '^^iiiiii^^^';
  Part[5, 10] := '^^^^^+^^^^^';
  Part[5, 11] := '^^^^^i^^^^^';

  Part[6, 1]  := '^^^^^i^^^^^';
  Part[6, 2]  := '^^iiiiiii^^';
  Part[6, 3]  := '^iiiiiiiii^';
  Part[6, 4]  := '^i^iiiii^i^';
  Part[6, 5]  := '^i^^iii^^i^';
  Part[6, 6]  := 'iii^^^^^iii';
  Part[6, 7]  := '^ii.....ii^';
  Part[6, 8]  := '^i......ii^';
  Part[6, 9]  := '^iii.ii.ii^';
  Part[6, 10] := '^^i.....i^^';
  Part[6, 11] := '^^^^^i^^^^^';

  Part[7, 1]  := '^^^^^i^^^^^';
  Part[7, 2]  := '^^^^^i^^^^^';
  Part[7, 3]  := '^iiiiii^^^^';
  Part[7, 4]  := '^iiiiiii^^^';
  Part[7, 5]  := '^ii..iiii^^';
  Part[7, 6]  := 'iiiiicciiii';
  Part[7, 7]  := '^iiiiiicci^';
  Part[7, 8]  := '^^iiii.iii^';
  Part[7, 9]  := '^^^iii.iii^';
  Part[7, 10] := '^^^^^i.iii^';
  Part[7, 11] := '^^^^^i^^^^^';

  Part[8, 1]  := '^^^^^+^^^^^';
  Part[8, 2]  := '^^^^^ii.^^^';
  Part[8, 3]  := '^^ii^^^.i^^';
  Part[8, 4]  := '^^ii^i^^i^^';
  Part[8, 5]  := '^^ii^i^^i^^';
  Part[8, 6]  := '^^ii^iiiiii';
  Part[8, 7]  := '^^^iiii^ii^';
  Part[8, 8]  := '^^^^^i^^i^^';
  Part[8, 9]  := '^^^^^i^i^^^';
  Part[8, 10] := '^^^^^^i^^^^';
  Part[8, 11] := '^^^^^i^^^^^';

  Part[9, 1]  := '^^^^^i^^^^^';
  Part[9, 2]  := '^^^^^i^^^^^';
  Part[9, 3]  := '^.^^^^i^^^^';
  Part[9, 4]  := '^.^^^^^i^^^';
  Part[9, 5]  := '^.^^^^^^i^^';
  Part[9, 6]  := '.......^iii';
  Part[9, 7]  := '^i^^^^^^i^^';
  Part[9, 8]  := '^^i^^^^^i^^';
  Part[9, 9]  := '^^^i^^^^i^^';
  Part[9, 10] := '^^^^iiiiii^';
  Part[9, 11] := '^^^^^+^^^^^';

  Part[10, 1]  := '^^^^^+^^^^^';
  Part[10, 2]  := '^^^^^.^^^^^';
  Part[10, 3]  := '^i.i^ii^^^^';
  Part[10, 4]  := '^i.^iii^^^^';
  Part[10, 5]  := '^ci^ii^^i^^';
  Part[10, 6]  := '+cii^^^iii+';
  Part[10, 7]  := '^cii^^iiii^';
  Part[10, 8]  := '^^ii^^iiii^';
  Part[10, 9]  := '^^^ii.iii^^';
  Part[10, 10] := '^^^^^.iii^^';
  Part[10, 11] := '^^^^^+^^^^^';

  Part[11, 1]  := '^i^iiiiiiii';
  Part[11, 2]  := '^i^iiiiiiii';
  Part[11, 3]  := '^i^^iiiiiii';
  Part[11, 4]  := '^ii^^i^^iii';
  Part[11, 5]  := 'iiiiiii^^ii';
  Part[11, 6]  := 'iii^iiii^^i';
  Part[11, 7]  := 'iii^^iiii^i';
  Part[11, 8]  := '^iii^^iii^i';
  Part[11, 9]  := '^iiii^^ii^i';
  Part[11, 10] := '^^iiii^ii^i';
  Part[11, 11] := '^^^iii^^^^i';

  Part[12, 1]  := '^^^^^+^^^^^';
  Part[12, 2]  := '^^^^^iiii^^';
  Part[12, 3]  := '^^^^^i^^^i^';
  Part[12, 4]  := '^^^^^i^^^i^';
  Part[12, 5]  := '^^^^icc^^i^';
  Part[12, 6]  := 'i^^^i^^^^^i';
  Part[12, 7]  := '^i^^+^^^^^^';
  Part[12, 8]  := '^i^^i^^^^^^';
  Part[12, 9]  := '^i^^ii^^^^^';
  Part[12, 10] := '^^iiii^^^^^';
  Part[12, 11] := '^^^^^i^^^^^';

  Part[13, 1]  := '^^^^^i^^^^^';
  Part[13, 2]  := '^^^^^iiii^^';
  Part[13, 3]  := '^^^^^i^^^i^';
  Part[13, 4]  := '^^^^^i^^^i^';
  Part[13, 5]  := '^^^^^i^^^i^';
  Part[13, 6]  := 'i^^^i^^^^^i';
  Part[13, 7]  := '^i^^i^^^^^^';
  Part[13, 8]  := '^i^^i^^^^^^';
  Part[13, 9]  := '^i^^^i^^^^^';
  Part[13, 10] := '^^iiii^^^^^';
  Part[13, 11] := '^^^^^i^^^^^';

  Part[14, 1]  := '^^^^^i^^^^^';
  Part[14, 2]  := '^^^^^i^^^^^';
  Part[14, 3]  := '^^^iiii^^^^';
  Part[14, 4]  := '^iiii^^^^^^';
  Part[14, 5]  := '^ii^^^iii^^';
  Part[14, 6]  := 'ii^^ii..ii+';
  Part[14, 7]  := '^i+ii....i^';
  Part[14, 8]  := '^^^iii..ii^';
  Part[14, 9]  := '^^^ii...i^^';
  Part[14, 10] := '^^^^^i.i^^^';
  Part[14, 11] := '^^^^^+^^^^^';

  Part[15, 1]  := '^^^iii^^^^^';
  Part[15, 2]  := '^^iiii^^^^^';
  Part[15, 3]  := 'iiiii^^^^^^';
  Part[15, 4]  := '^iiiii^^^^^';
  Part[15, 5]  := '^^iiiiiiii^';
  Part[15, 6]  := 'iiiiiiiiiii';
  Part[15, 7]  := '^^iiiiiii^^';
  Part[15, 8]  := '^iiiiiii^^^';
  Part[15, 9]  := '^^^^iiiiii^';
  Part[15, 10] := '^^^^iiii^^^';
  Part[15, 11] := '^^^^^i^^^^^';

  Part[16, 1]  := '^^^iiiiii^^';
  Part[16, 2]  := '^^ii.iiiiii';
  Part[16, 3]  := 'iiii.iiiiii';
  Part[16, 4]  := '^iiii.ii^^^';
  Part[16, 5]  := '^^iiii.iii^';
  Part[16, 6]  := 'iiiii^.....';
  Part[16, 7]  := '^^i^^i.ii^^';
  Part[16, 8]  := '^iiii.iiiii';
  Part[16, 9]  := '^^^ii.iiii^';
  Part[16, 10] := '^^^^i.ii^^^';
  Part[16, 11] := '^^^ii.iii^^';

  Part[17, 1]  := '^^^^^i^^^^^';
  Part[17, 2]  := '^^^^^i^^^^^';
  Part[17, 3]  := '^^^iiii^^^^';
  Part[17, 4]  := '^iiii^^^^^^';
  Part[17, 5]  := '^ii^^^iii^^';
  Part[17, 6]  := 'il^^llllii+';
  Part[17, 7]  := '^lllllllll^';
  Part[17, 8]  := '^^^lllllll^';
  Part[17, 9]  := '^^^llllll^^';
  Part[17, 10] := '^^^^^lll^^^';
  Part[17, 11] := '^^^^^l^^^^^';

  Part[18, 1]  := '^^^^^ll^^^^';
  Part[18, 2]  := '^^lliilll^^';
  Part[18, 3]  := '^lilllllll^';
  Part[18, 4]  := '^l^iiiii^i^';
  Part[18, 5]  := '^il^iii^^i^';
  Part[18, 6]  := 'iiilll^^lll';
  Part[18, 7]  := '^ii..llllil';
  Part[18, 8]  := '^i.lllllll^';
  Part[18, 9]  := '^iiilll.ii^';
  Part[18, 10] := '^^i..l..i^^';
  Part[18, 11] := '^^^^llll^^^';

  Part[19, 1]  := '^^^^^l^^^^^';
  Part[19, 2]  := '^^iiiliii^^';
  Part[19, 3]  := '^iiiiliiii^';
  Part[19, 4]  := '^i^iliii^i^';
  Part[19, 5]  := '^i^^lii^^i^';
  Part[19, 6]  := 'iii^l^^^iii';
  Part[19, 7]  := '^iii.l..ii^';
  Part[19, 8]  := '^i.i.l..ii^';
  Part[19, 9]  := '^iii.li.ii^';
  Part[19, 10] := '^^i...l.i^^';
  Part[19, 11] := '^^^^^ll^^^^';

  if lvl = 15 then
  begin
    Part[20, 1]  := '^^^iii^^^^^';
    Part[20, 2]  := '^^iiii^^^^^';
    Part[20, 3]  := 'iiiii^^^^^^';
    Part[20, 4]  := '^i###+###^^';
    Part[20, 5]  := '^^#-----#i^';
    Part[20, 6]  := 'ii+-----+ii';
    Part[20, 7]  := '^^#-----#^^';
    Part[20, 8]  := '^i###+##^^^';
    Part[20, 9]  := '^^^^iiiiii^';
    Part[20, 10] := '^^^^iiii^^^';
    Part[20, 11] := '^^^^^i^^^^^';

    Part[21, 1]  := '^iii^^#####';
    Part[21, 2]  := '^^iii^#---#';
    Part[21, 3]  := 'iiiii^#---#';
    Part[21, 4]  := '^iiiii#---#';
    Part[21, 5]  := '^^ii^^###+#';
    Part[21, 6]  := 'iii^^^^^iii';
    Part[21, 7]  := '^^iiiiiii^^';
    Part[21, 8]  := '^^^iiii^^^^';
    Part[21, 9]  := '^^iii^^^^^^';
    Part[21, 10] := '^iiiiii^^^^';
    Part[21, 11] := '^^^^^i^^^^^';

    Part[22, 1]  := '^^^iii^^ii^';
    Part[22, 2]  := '^^iiii^^iii';
    Part[22, 3]  := 'iiiii^^^iii';
    Part[22, 4]  := '^^####ii^i^';
    Part[22, 5]  := '^^#--+iiii^';
    Part[22, 6]  := 'ii####iiiii';
    Part[22, 7]  := 'iiiiiiiiiii';
    Part[22, 8]  := 'iiii^^iiiii';
    Part[22, 9]  := '^ii^ii##+##';
    Part[22, 10] := '^iiiii#---#';
    Part[22, 11] := '^^^^^i#####';

    TotalParts := 22;
  end
  else
    TotalParts := 19;
end;

