if lvl = 20 then
begin
  // lava, rock and great halls
  Part[1, 1]  := 'lllllllllll';
  Part[1, 2]  := 'lllllllllll';
  Part[1, 3]  := 'll^^lllllll';
  Part[1, 4]  := 'lll^^llllll';
  Part[1, 5]  := 'lllllllllll';
  Part[1, 6]  := 'lllllllllll';
  Part[1, 7]  := 'lllll^^llll';
  Part[1, 8]  := 'llllll^llll';
  Part[1, 9]  := 'lllllll^lll';
  Part[1, 10] := 'lllllllllll';
  Part[1, 11] := 'lllllllllll';

  Part[2, 1]  := 'llll^+^llll';
  Part[2, 2]  := 'll^^^.^^^ll';
  Part[2, 3]  := 'l^^.....^^l';
  Part[2, 4]  := 'l^.......^l';
  Part[2, 5]  := '^^.......^^';
  Part[2, 6]  := '+.........+';
  Part[2, 7]  := '^^.......^^';
  Part[2, 8]  := 'l^^.....^^l';
  Part[2, 9]  := 'll^^^+^^^ll';
  Part[2, 10] := 'llll^.^llll';
  Part[2, 11] := 'llll^.^llll';

  Part[3, 1]  := 'lll^^.^^lll';
  Part[3, 2]  := 'll^^...^^ll';
  Part[3, 3]  := 'l^^.....^^l';
  Part[3, 4]  := 'l^.......^l';
  Part[3, 5]  := '^^.......^^';
  Part[3, 6]  := '...........';
  Part[3, 7]  := '^^.......^^';
  Part[3, 8]  := 'l^.......^l';
  Part[3, 9]  := 'l^.......^l';
  Part[3, 10] := 'l^^.....^^l';
  Part[3, 11] := 'll^^^.^^^ll';

  Part[4, 1]  := 'll^......^^';
  Part[4, 2]  := 'l^^.......^';
  Part[4, 3]  := '^^.......^^';
  Part[4, 4]  := '^^........^';
  Part[4, 5]  := 'l^^^^....^^';
  Part[4, 6]  := 'll^^^^..^^^';
  Part[4, 7]  := 'l^^^.....^l';
  Part[4, 8]  := 'l^.....^^^l';
  Part[4, 9]  := '^^......^^^';
  Part[4, 10] := 'l^^^.....^^';
  Part[4, 11] := 'll^^^.^^^^l';

  Part[5, 1]  := 'lllll.lllll';
  Part[5, 2]  := 'llll..lllll';
  Part[5, 3]  := 'llll..lllll';
  Part[5, 4]  := 'lllll.lllll';
  Part[5, 5]  := 'lllll..ll.l';
  Part[5, 6]  := '...........';
  Part[5, 7]  := 'll....ll...';
  Part[5, 8]  := 'lllll.lllll';
  Part[5, 9]  := 'lllll.lllll';
  Part[5, 10] := 'lllll..llll';
  Part[5, 11] := 'lllll.lllll';

  Part[6, 1]  := 'llll^.^llll';
  Part[6, 2]  := 'll^^^.^^^ll';
  Part[6, 3]  := 'l^^.....^^l';
  Part[6, 4]  := 'l^...^...^l';
  Part[6, 5]  := '^^...^...^^';
  Part[6, 6]  := '...^.^^....';
  Part[6, 7]  := '^^....^..^^';
  Part[6, 8]  := 'l^^...^.^^l';
  Part[6, 9]  := 'll^^^.^^^ll';
  Part[6, 10] := 'llll^.^llll';
  Part[6, 11] := 'llll^.^llll';

  Part[7, 1]  := 'lll^^.^^lll';
  Part[7, 2]  := 'll^^...^^ll';
  Part[7, 3]  := 'l^^..^..^^l';
  Part[7, 4]  := 'l^...^.^.^l';
  Part[7, 5]  := '^^^^^....^^';
  Part[7, 6]  := '....^^^^...';
  Part[7, 7]  := '^^...^...^^';
  Part[7, 8]  := 'l^.^.^...^l';
  Part[7, 9]  := 'l^...^^..^l';
  Part[7, 10] := 'l^^.....^^l';
  Part[7, 11] := 'll^^^.^^^ll';

  Part[8, 1]  := 'lll^^.^^^ll';
  Part[8, 2]  := 'l^^^^...^^l';
  Part[8, 3]  := '^^..^^^..^^';
  Part[8, 4]  := '^^..^.^^.^^';
  Part[8, 5]  := '^^..^.^^.^^';
  Part[8, 6]  := '^^..^......';
  Part[8, 7]  := '^^^....^..^';
  Part[8, 8]  := 'l^^^^.^^.^^';
  Part[8, 9]  := 'll^^^.^.^^l';
  Part[8, 10] := 'lll^^^.^^ll';
  Part[8, 11] := 'llll^.^^lll';

  Part[9, 1]  := 'l^^^^.^^^ll';
  Part[9, 2]  := '^^^^^.^^^^l';
  Part[9, 3]  := '^.^^^^.^^^^';
  Part[9, 4]  := '^.^^^^^.^^^';
  Part[9, 5]  := '^.^^^^^^.^^';
  Part[9, 6]  := '.......^...';
  Part[9, 7]  := '^.^^^^^^.^^';
  Part[9, 8]  := '^^.^^^^^.^^';
  Part[9, 9]  := '^^^.^^^^.^^';
  Part[9, 10] := 'l^^^......^';
  Part[9, 11] := 'lll^^.^^^^^';

  Part[10, 1]  := 'llll^.^llll';
  Part[10, 2]  := 'l^^^^.^^^ll';
  Part[10, 3]  := '^^.....^^^l';
  Part[10, 4]  := '^....l..^^l';
  Part[10, 5]  := '^...lll..^^';
  Part[10, 6]  := '..lllllll..';
  Part[10, 7]  := '^..lllll..^';
  Part[10, 8]  := '^^..lll.^^';
  Part[10, 9]  := '^^^...l..^l';
  Part[10, 10] := 'l^^^....^^l';
  Part[10, 11] := 'lll^^.^^^ll';

  Part[11, 1]  := '^.^llllllll';
  Part[11, 2]  := '^.^llllllll';
  Part[11, 3]  := '^.^^lllllll';
  Part[11, 4]  := '^..^^.^^lll';
  Part[11, 5]  := '.......^^ll';
  Part[11, 6]  := '...^....^^l';
  Part[11, 7]  := '...^^....^l';
  Part[11, 8]  := '^...^^...^l';
  Part[11, 9]  := '^....^^..^l';
  Part[11, 10] := '^^....^.^^l';
  Part[11, 11] := 'l^^...^^^ll';

  Part[12, 1]  := 'lllllll.lll';
  Part[12, 2]  := 'llllll.llll';
  Part[12, 3]  := 'lllll.lllll';
  Part[12, 4]  := 'lllll.lllll';
  Part[12, 5]  := 'llllll....l';
  Part[12, 6]  := 'lll...l.ll.';
  Part[12, 7]  := '...lll..lll';
  Part[12, 8]  := 'lllllll.lll';
  Part[12, 9]  := 'lllll..llll';
  Part[12, 10] := 'lllll.lllll';
  Part[12, 11] := 'lllll.lllll';

  Part[13, 1]  := 'llllllll^.^';
  Part[13, 2]  := 'llllllll^.^';
  Part[13, 3]  := 'll^^^ll^..^';
  Part[13, 4]  := 'l^^.^^l^.^l';
  Part[13, 5]  := '^.....^^.^l';
  Part[13, 6]  := '..^^.......';
  Part[13, 7]  := '^...^^^^.^l';
  Part[13, 8]  := '^........^l';
  Part[13, 9]  := '^...^^...^l';
  Part[13, 10] := '^^....^.^^l';
  Part[13, 11] := 'l^^^^.^^^ll';

  TotalParts := 13;
end;

